server:
  port: 4000
spring:
  application:
    name: customer
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/customer
    password: Amir12345
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  zipkin:
    base-url: http://localhost:9411
  rabbitmq:
    addresses: localhost:5672
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761
    fetch-registry: true
    register-with-eureka: true