services:
  #  postgres:
  #    container_name: postgres
  #    image: postgres
  #    environment:
  #      POSTGRES_USER: amigoscode
  #      POSTGRES_PASSWORD: password
  #      PGDATA: /data/postgres
  #    volumes:
  #      - postgres_data:/data/postgres
  #    ports:
  #      - "5432:5432"
  #    networks:
  #      - postgres
  #    restart: unless-stopped
  #
  #  pgadmin:
  #    container_name: pgadmin
  #    image: dpage/pgadmin4
  #    environment:
  #      PGADMIN_DEFAULT_EMAIL: fathiamir37@gmail.com
  #      PGADMIN_DEFAULT_PASSWORD: amir12345
  #      PGADMIN_CONFIG_SERVER_MODE: 'False'
  #    volumes:
  #      - pgadmin_data:/var/lib/pgadmin
  #    ports:
  #      - "5050:80"
  #    networks:
  #      - postgres
  #    restart: unless-stopped
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - 9411:9411
  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
networks:
  postgres:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data:
