server:
  port: 5000
spring:
  application:
    name: fraud
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/fraud
    password: Amir12345
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761
    fetch-registry: true
    register-with-eureka: true